# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Widget-Factory
version:      0.01
version_from: lib/HTML/Widget/Factory.pm
installdirs:  site
requires:
    HTML::Element:                 0
    List::MoreUtils:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
