---
abstract: 'churn out HTML widgets'
author:
  - 'Ricardo SIGNES <C<rjbs @ cpan.org>>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: HTML::Widget::Factory
name: HTML-Widget-Factory
no_index:
  directory:
    - inc
    - t
requires:
  HTML::Element: 0
  List::MoreUtils: 0
  Module::Pluggable: 2.9
  Package::Generator: 0.1
  Package::Reaper: 0.1
  Sub::Install: 0
  UNIVERSAL::require: 0.1
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.068
